### ISSUE TITLE
Is there a way to remove the scrollbar

### ISSUE THREAD

**Issue by markawili** [nhn/toast-ui.react-calendar#70]
## Version

"@toast-ui/react-calendar": "^1.0.6",

## Test Environment

windows 10
microsoft edge

## Current Behavior

As title suggests, just wanted to ask if there is a way to remove the scrollbar in the calendar?

**Comment by adhrinae** [comment]
@markawili 

Yes, You can override the default CSS rules.

For instance, to hide the scrollbars in the week view:

```css
.tui-full-calendar-dayname-container {
  overflow-y: hidden;
}

.tui-full-calendar-weekday-grid {
  overflow-y: hidden;
}

.tui-full-calendar-weekday-schedules {
  overflow-y: hidden;
}

.tui-full-calendar-timegrid-container {
  overflow-y: hidden;
}
```

Example: https://stackblitz.com/edit/tui-calendar-playground-rk2ia1?file=index.js

---

You can find all of the CSS rules showing scrollbars [here](https://github.com/nhn/tui.calendar/search?q=overflow-y%3A+scroll).
